---
title: "Geocoding"
author: "Xiaomeng Zhou"
date: "4/18/2022"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
```

## loading libraries


```{r}
library(dplyr)
library(tidyverse)
#install.packages('tidygeocoder')
library(tidygeocoder)

```

## loading data and combine address based on "Location""Area" and "Country"
```{r}
df <- read.csv("data/sharks.csv")

df <- mutate(df, address = paste(Location,",", Area,",", Country))

addr <- as.data.frame(unique(df$address))

# rename column
names(addr)[names(addr)=="unique(df$address)"] <- "addr_combine" 
colnames(addr)

```


## Geocoding 

```{r}
lat_longs <- addr %>%
  geocode(addr_combine, method = 'arcgis', lat = latitude , long = longitude)

```

```{r}
lat_longs
```
## Add longtitude and lantitude columns to orignal dataframe
```{r}
df <- left_join(df,lat_longs,by= c("address" = "addr_combine"))
```

## output csv
```{r}
write.csv(df,"sharks_geocoding.csv", row.names = FALSE)
```



```{r}
some_addresses <- tibble::tribble(
~name,                  ~addr,
"White House",          "Hawaii,USA",
"Transamerica Pyramid", "600 Montgomery St, San Francisco, CA 94111",     
"Willis Tower",         "233 S Wacker Dr, Chicago, IL 60606"                                  
)

# geocode the addresses
lat_longs <- some_addresses %>%
  geocode(addr, method = 'osm', lat = latitude , long = longitude)
#> Passing 3 addresses to the Nominatim single address geocoder
#> Query completed in: 3 seconds
```
```{r}
lat_longs
```

